### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection

### ISSUE THREAD

**Issue by oldboy-snt** [lucasbaizer2/hasmer#2]
hasmer.exe decompile -i index.android.bundle
25433
3
13330
10000000000000000000000011111111
10111101000111
10000000000000000011001100010011
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Hasmer.Decompiler.Analysis.ControlFlowGraph.BuildControlFlowBlocks() in libhasmer\Decompiler\Analysis\ControlFlowGraph.cs:line 120
   at Hasmer.Decompiler.Analysis.ControlFlowGraph..ctor(HbcFile file, List`1 instructions) in \hasmer\hasmer\libhasmer\Decompiler\Analysis\ControlFlowGraph.cs:line 44
   at Hasmer.Decompiler.FunctionDecompiler.CreateAST(DecompilerContext parent) in \hasmer\hasmer\libhasmer\Decompiler\FunctionDecompiler.cs:line 138
   at Hasmer.Decompiler.HbcDecompiler.Decompile(Boolean preserveAst) in \hasmer\hasmer\libhasmer\Decompiler\HbcDecompiler.cs:line 68
   at Hasmer.CLI.Program.Decompile(DecompileOptions options) in \hasmer\hasmer\hasmer-cli\Program.cs:line 164
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Hasmer.CLI.Program.Main(String[] args) in \hasmer\hasmer\hasmer-cli\Program.cs:line 76

**Comment by oldboy-snt** [comment]
Yeah, I tried disassembler and it' worked
